name: filmov
description: A new Flutter application.

publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  get_it: ^7.2.0
  http: ^0.13.4
  share: ^2.0.4
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^8.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/movie.json

flutter_native_splash:

  color: "#764BC4"
  image: assets/images/logo.png
